version: '3.8'
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    restart: always
    container_name: cdm_mailhog
    ports:
      - '1025:1025'
      - '9001:8025'
    networks:
      - symfony
    external_links:
      - mailhog
  mysql:
    image: 'mysql:8.0.31'
    working_dir: /application
    volumes:
      - '.:/application'
    container_name: cdm_mysql
    restart: always
    ports:
      - '9002:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdd_cup_of_the_world_2022
    networks:
      - symfony
  webserver:
    image: 'nginx:alpine'
    restart: always
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '9003:80'
    networks:
      - symfony
    container_name: cdm_webserver
  php-fpm:
    build: docker/php-fpm
    working_dir: /application
    restart: always
    volumes:
      - '.:/application'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    networks:
      - symfony
    container_name: cdm_php
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: cdm_phpmyadmin
    restart: always
    ports:
      - '9004:80'
    environment:
      PMA_HOST: mysql
    networks:
      - symfony
networks:
  symfony:
